project:
  name: quickstart-cloudera
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
    - ap-northeast-1
    # - ap-northeast-2
    # - ap-southeast-1
    # - ap-southeast-2
    # - ap-south-1
    # - eu-central-1
    # - eu-west-1
    # - sa-east-1
    # - us-east-1
    # - us-east-2
    # - us-west-1
    # - us-west-2
  s3_bucket: ''
tests:
  withVPC:
    parameters:
      AvailabilityZones: $[taskcat_getaz_2]
      ClusterLauncherType: m4.large
      KeyName: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: quickstart-cloudera/
      RemoteAccessCIDR: 10.0.0.0/32
    regions:
      - ap-northeast-1
      # - ap-northeast-2
      # - ap-southeast-1
      # - ap-southeast-2
      # - ap-south-1
      # - eu-central-1
      # - eu-west-1
      # - sa-east-1
      # - us-east-1
      # - us-east-2
      # - us-west-1
      # - us-west-2
    s3_bucket: ''
    template: templates/cloudera-master.template.yml
