project:
  name: quickstart-cloudera
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
    - ap-northeast-1
  s3_bucket: ''
tests:
  withVPC:
    parameters:
      ClusterLauncherType: m4.large
      KeyName: override
      PrivateCIDR: 10.0.0.0/19
      PrivateSubnet: subnet-0dbb136f56a82cf3d
      PublicCIDR: 10.0.128.0/20
      PublicSubnet: subnet-0aca7739512f5f901
      QSS3BucketName: tcat-0eab2dca75865eb1b038a256aa258635-ap-northeast-1
      QSS3BucketRegion: ap-northeast-1
      QSS3KeyPrefix: quickstart-cloudera/
      RemoteAccessCIDR: 10.0.0.0/32
      VPC: vpc-0506bf9a674af5de7
    regions:
      - ap-northeast-1
    s3_bucket: ''
    template: templates/cloudera.template.yml
